FROM public.ecr.aws/lambda/python:3.9

# Copy requirements from root
COPY requirements.txt ${LAMBDA_TASK_ROOT}/
RUN pip install --no-cache-dir -r ${LAMBDA_TASK_ROOT}/requirements.txt

# Copy application code
COPY src/*.py ${LAMBDA_TASK_ROOT}/

# Copy templates directory if it exists
COPY src/templates ${LAMBDA_TASK_ROOT}/templates/

CMD ["lambda_handler.handler"]