name: Environment Tests

on:
  push:
    branches:
      - main
      - stage
  pull_request:
    branches:
      - main
      - stage

jobs:
  test:
    name: Environment Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # This is where tests can be added for each commit
    - name: Run tests
      run: | 
        echo "Test placeholder"

    # Different environments (stage, prod, etc) would also have some tests
    # specific to that environment. Those should go in another workflow
    # triggered by the specific branch for the environment in question
