name: Environment Tests

on:
  push:
    branches:
      - main
      - stage
  pull_request:
    branches:
      - main
      - stage

jobs:
  test:
    name: Environment Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

      ########################
      # Run unit tests 
      ########################

    # Init python, install dependencies, and test our app.
    - name: Initialize Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.python-version}}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt    

    - name: Test app
      run: |
        pytest src/


    # Different environments (stage, prod, etc) would also have some tests
    # specific to that environment. Those should go in another workflow
    # triggered by the specific branch for the environment in question
